version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      NODE_ENV: production
      MONGO_HOST: mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
